In [3]:
import re

text = "Hello, world. Is this-- a test?"
result = re.split(r'([,.:;?_!"()\']|--|\s)', text)
result = [item.strip() for item in result if item.strip()]
print(result)

['Hello', ',', 'world', '.', 'Is', 'this', '--', 'a', 'test', '?']


In [6]:
import torch
import torch.nn as nn

# 词汇表有 10000 个词，每个词用 256 维向量表示
embedding = nn.Embedding(10000, 3)

# 查看参数（权重矩阵）
print(embedding.weight.shape)  # torch.Size([10000, 256])

torch.Size([10000, 3])


In [7]:
# 查询 token ID = 5 的向量
token_id = torch.tensor([5])
vector = embedding(token_id)

print(vector.shape)  # torch.Size([1, 256])
print(vector)

torch.Size([1, 3])
tensor([[-2.2691,  0.2763,  0.6760]], grad_fn=<EmbeddingBackward0>)


In [8]:
# 多个 token IDs
token_ids = torch.tensor([1, 3, 5, 7])  # shape: [4]
vectors = embedding(token_ids)

print(vectors.shape)  # torch.Size([4, 256])

torch.Size([4, 3])


In [9]:
# 最常见的用法：batch size = 2, sequence length = 3
token_ids = torch.tensor([
    [1, 3, 5],   # 第一个样本的3个token
    [2, 4, 6]    # 第二个样本的3个token
])  # shape: [2, 3]

vectors = embedding(token_ids)
print(vectors.shape)  # torch.Size([2, 3, 256])

torch.Size([2, 3, 3])


In [10]:
embedding = nn.Embedding(6, 4)
token_ids = torch.tensor([0, 2, 4])
result = embedding(token_ids)  # 一行代码搞定

In [11]:
result

tensor([[ 0.0325, -0.6049,  1.1947, -0.8290],
        [-0.3889, -0.2916, -0.0485,  0.7723],
        [ 1.0930, -0.6172,  0.4538,  0.9101]], grad_fn=<EmbeddingBackward0>)

In [14]:
# Embedding 层的权重实际上是一个矩阵
weight_matrix = torch.randn(6, 4)  # [vocab_size, embed_dim]
print(weight_matrix)
# one-hot 编码 + 矩阵乘法
token_ids = torch.tensor([0, 2, 4])

# 创建 one-hot 矩阵
one_hot = torch.zeros(3, 6)  # [num_tokens, vocab_size]
one_hot[0, 0] = 1  # token 0
one_hot[1, 2] = 1  # token 2
one_hot[2, 4] = 1  # token 4
print(one_hot)
# 矩阵乘法
result = one_hot @ weight_matrix  # [3, 6] @ [6, 4] = [3, 4]

print(result.shape)  # torch.Size([3, 4])

tensor([[ 1.3700,  0.2907, -1.1695,  1.8348],
        [-1.3195, -0.5754, -0.2201,  0.7729],
        [ 0.4219, -0.5791, -1.9384, -1.4536],
        [ 0.5826, -0.6885, -0.0192, -0.4468],
        [-0.4237,  2.4523, -0.0211, -0.1159],
        [ 0.4879, -0.7526, -1.5180,  0.8263]])
tensor([[1., 0., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 0., 1., 0.]])
torch.Size([3, 4])


In [15]:
import torch
import torch.nn as nn

# 1. 假设我们有一个很小的词汇表
vocab = {
    'hello': 0,
    'world': 1,
    'how': 2,
    'are': 3,
    'you': 4,
    '?': 5
}
vocab_size = len(vocab)  # 6

# 2. 创建 Embedding 层
embed_dim = 8
embedding = nn.Embedding(vocab_size, embed_dim)

# 3. 一句话："hello world how are you ?"
token_ids = torch.tensor([0, 1, 2, 3, 4, 5])  # shape: [6]

# 4. 获取嵌入
embeddings = embedding(token_ids)  # shape: [6, 8]

print(f"Token IDs: {token_ids}")
print(f"嵌入 shape: {embeddings.shape}")
print(f"第一个 token 'hello' 的嵌入: {embeddings[0]}")

Token IDs: tensor([0, 1, 2, 3, 4, 5])
嵌入 shape: torch.Size([6, 8])
第一个 token 'hello' 的嵌入: tensor([ 0.7167, -0.2753,  0.2193,  0.7653, -0.4508, -0.7511,  2.0213,  1.4483],
       grad_fn=<SelectBackward0>)
